Adds api get opportunities of agent, tests and documentation.
secultce/mapacultural pull request #151
Opened 2024-04-16 21:33 UTC by Akellymourab

Fix #111

2024-04-16 21:40 UTC, saracamilodev approved these changes

2024-04-16 21:42 UTC, TalysonSoares approved these changes

2024-04-17 13:02 UTC, alessandrofeitoza requested changes
Algumas modificações pequenas

2024-04-17 13:02 UTC, alessandrofeitoza commented on app/src/Repository/AgentRepository.php
> +    public function getAgentOpportunities(int $agentId): array
Acredito que por se tratar de Oportunidades (o objeto em questão), o ideal seria que esse método fosse na classe `OpportunityRepository` 

e tbm a assinatura do método poderia ser `findOpportunitiesByAgentId(int $agentId)`

2024-04-17 13:02 UTC, alessandrofeitoza commented on app/src/Repository/AgentRepository.php
> +        $qb = $this->repository
O nome da variável pode ser `$queryBuilder` ao invés de `$qb`, pois isso o tornaria mais legivel

2024-04-17 18:54 UTC, alessandrofeitoza approved these changes

2024-04-17 18:55 UTC, merged