Add fixtures command
secultce/mapacultural pull request #167
Opened 2024-04-23 00:10 UTC by henriquelopeslima

Resolve #130

2024-04-23 00:11 UTC, Akellymourab approved these changes

2024-04-24 17:39 UTC, alessandrofeitoza commented on app/src/Command/FixturesCommand.php
> +            '== INSTALL DATA FIXTURES ==',
acho que `RUN DATA FIXTURES` combina mais, pq pressupomos que a lib já esteja instalada.

2024-04-24 17:39 UTC, alessandrofeitoza commented on app/src/Command/FixturesCommand.php
> +        $this->setDescription('Install data fixtures to MapaCultural.');
o mesmo vale pra cá: `Run data fixtures to MapaCultural.`

2024-04-24 17:40 UTC, alessandrofeitoza requested changes
só essas coisinhas mesmo, e eu aprovo

2024-04-24 18:02 UTC, alessandrofeitoza approved these changes

2024-04-24 18:02 UTC, merged