Adds delete endpoint for Space.
secultce/mapacultural pull request #172
Opened 2024-04-25 17:50 UTC by saracamilodev

#137

2024-04-25 19:44 UTC, alessandrofeitoza commented on app/src/Controller/Api/SpaceApiController.php
> +        }
acho que a validação não está correta, deveria talvez ser:
```php
        if (-10 === $space->status) {
 ```

2024-04-25 19:45 UTC, alessandrofeitoza requested changes
só uma modificação, e eu aprovo

2024-04-25 19:54 UTC, saracamilodev commented on app/src/Controller/Api/SpaceApiController.php
> +        }
Feito a modificação.

2024-04-25 20:35 UTC, alessandrofeitoza approved these changes

2024-04-26 13:15 UTC, TalysonSoares approved these changes

2024-04-26 13:39 UTC, merged