Added Opportunity create endpoint.
secultce/mapacultural pull request #192
Opened 2024-05-01 18:01 UTC by saracamilodev

2024-05-01 19:08 UTC, Akellymourab commented on app/src/Controller/Api/OpportunityApiController.php
Abaixo da linha 15 é importante adicionar 
``` 
    private OpportunityRequest $opportunityRequest;
    private OpportunityService $opportunityService; 
```

2024-05-01 19:21 UTC, Akellymourab requested changes

2024-05-01 19:21 UTC, Akellymourab commented on app/src/Controller/Api/OpportunityApiController.php
Abaixo da linha 15 é importante adicionar
```
    private OpportunityRequest $opportunityRequest;
    private OpportunityService $opportunityService; 
```

2024-05-02 18:13 UTC, Akellymourab requested changes

2024-05-02 18:13 UTC, Akellymourab commented on app/src/Service/OpportunityService.php
> +        $opportunity->setTitle($data['title']);
acredito que seja interessante usar a função setName correspondente da entidade Opportunity:
```
$opportunity->setName($data['title']);
```

2024-05-02 18:13 UTC, Akellymourab commented on app/src/Service/OpportunityService.php
> +        $opportunity->setInterestArea($data['interestArea']);
para acessar a area de interesse, assim deve funcionar:

```
$opportunity->terms['area'] = $data->terms['area'];
```

2024-05-02 18:13 UTC, Akellymourab commented on app/src/Controller/Api/OpportunityApiController.php
>          $this->repository = new OpportunityRepository();
é importante adicionar esse trecho abaixo: 
```
 $this->opportunityRequest = new OpportunityRequest();
 $this->opportunityService = new OpportunityService();
```

2024-05-02 18:13 UTC, Akellymourab commented on app/src/Service/OpportunityService.php
> +        }
observando melhor a tabela de oportunidades no banco de dados eu notei que a coluna responsável por esses dados se chama `object_type`, observando também a entidade de oportunidade acredito que seria necessário criar uma função de `setObjectType` para poder acessa-la aqui na service, ficaria algo desse tipo: 
```
$opportunity->setObjectType("MapasCulturais\Entities\Project");
```

2024-05-02 18:13 UTC, Akellymourab commented on app/src/Controller/Api/OpportunityApiController.php
> +                'shortDescription' => $opportunity->getShortDescription(),
como `shortDescription` não está presente no service acredito que agora ele não será necessário

2024-05-02 18:13 UTC, Akellymourab commented on app/src/Controller/Api/OpportunityApiController.php
> +                'name' => $opportunity->getName(),
`name`, deve ser substituído por title para fazer correspondência ao que está em service

2024-05-02 18:13 UTC, Akellymourab commented on app/src/Request/OpportunityRequest.php
> +        $requiredFields = ['opportunityType', 'title', 'interestArea'];
`interestArea` pode ser substituido por apenas `area`

2024-05-02 18:13 UTC, Akellymourab commented on src/core/Entities/Opportunity.php
>  }
aqui você pode adicionar uma função para poder acessar o `object_type` no seu service

2024-05-08 13:42 UTC, TalysonSoares approved these changes

2024-05-09 12:21 UTC, henriquelopeslima commented on app/src/Controller/Api/OpportunityApiController.php
> +            return new JsonResponse($responseData, 201);
```suggestion
            return new JsonResponse($responseData, Response::HTTP_CREATED);
```

2024-05-09 12:21 UTC, henriquelopeslima commented on app/src/Controller/Api/OpportunityApiController.php
> +            return new JsonResponse(['error' => $exception->getMessage()], 404);
```suggestion
            return new JsonResponse(['error' => $exception->getMessage()], Response::HTTP_BAD_REQUEST);
```

2024-05-09 12:31 UTC, Akellymourab approved these changes

2024-05-09 13:48 UTC, merged