Adds patch endpoint for agent
secultce/mapacultural pull request #193
Opened 2024-05-02 17:52 UTC by TalysonSoares

#145 

**Campos que não estão sendo atualizados:**

- CPF
- CNPJ
- E-mail pessoal
- Telefone privado 1 com DDD
- Telefone privado 2 com DDD
- Complemento ou ponto de referência
- Data de nascimento
- Gênero
- Orientação sexual
- Raça/Cor
- Agente itinerante
- Tipo da conta bancária
- Dados bancários
- Comunidades tradicionais

**Campos que requerem validações específicas:**

- Site
- CPF
- CNPJ
- E-mail pessoal
- Telefone público
- E-mail público
- Telefone privado 1 com DDD
- Telefone privado 2 com DDD
- CEP

**Eventos incomuns:**

O campo `publicLocation` não atualiza no navegador, mas é atualizado no endpoint, que por sua vez atualiza no navegador.

**Não foram testados**

- Os campos de enviar imagens e arquivos.

2024-05-03 12:16 UTC, alessandrofeitoza commented on app/src/Service/AgentService.php
> +            }
talvez, para não precisar do else a gente pudesse dar um continue se entrar no if, tipo isso:

```php
if ('type' === $key) {
    $agent->setType($value);
    continue;
}

$agent->{$key} = $value;
```

2024-05-03 12:16 UTC, alessandrofeitoza requested changes
.

2024-05-09 12:14 UTC, henriquelopeslima commented on app/src/Controller/Api/AgentApiController.php
> +            return new JsonResponse($responseData, 201);
```suggestion
            return new JsonResponse($responseData, Response::HTTP_CREATED);
```

2024-05-09 12:17 UTC, henriquelopeslima commented on app/src/Controller/Api/AgentApiController.php
> +            return new JsonResponse(['error' => $exception->getMessage()], 400);
```suggestion
            return new JsonResponse(['error' => $exception->getMessage()], Response::HTTP_BAD_REQUEST);
```

2024-05-09 12:17 UTC, henriquelopeslima commented on app/src/Controller/Api/AgentApiController.php
> +        }
Essa validação pode ser feita no Service, já que você já faz a pesquisa no bando de dados. Fazendo ela aqui no Controller, acabamos fazendo uma query no banco sem necessidade.

2024-05-10 07:10 UTC, alessandrofeitoza requested changes

2024-05-10 07:10 UTC, alessandrofeitoza commented on app/src/Request/AgentRequest.php
> +        return $data;
acredito que aqui nós temos duas variaveis sendo criadas com um curto tempo de vida, talvez uma abordagem mais funcional resolva isso:

```php
return json_decode(
    json: $this->request->getContent(),
    associative: true
);
```

2024-05-10 07:10 UTC, alessandrofeitoza commented on app/src/Service/AgentService.php
> +    public function update($id, $data): Agent
estão faltando os tipos dos parametros

2024-05-10 07:10 UTC, alessandrofeitoza commented on app/src/Service/AgentService.php
> +        $agentUpdated = $this->serializer->denormalize($data, Agent::class, null, ['object_to_populate' => $agentFromDB]);
essa linha é muito longa, talvez valha essa refatoração a seguir:

```php
$agentUpdated = $this->serializer->denormalize(
    data: $data,
    type: Agent::class,
    context: ['object_to_populate' => $agentFromDB] 
);
```

2024-05-10 08:56 UTC, TalysonSoares commented on app/src/Request/AgentRequest.php
> +        return $data;
Boa

2024-05-14 12:46 UTC, henriquelopeslima approved these changes

2024-05-14 17:50 UTC, saracamilodev approved these changes

2024-05-15 12:54 UTC, alessandrofeitoza commented
**Campos que não estão sendo atualizados:**

- CPF
- CNPJ
- E-mail pessoal
- Telefone privado 1 com DDD
- Telefone privado 2 com DDD
- Complemento ou ponto de referência
- Data de nascimento
- Gênero
- Orientação sexual
- Raça/Cor
- Agente itinerante
- Tipo da conta bancária
- Dados bancários
- Comunidades tradicionais

**Campos que requerem validações específicas:**

- Site
- CPF
- CNPJ
- E-mail pessoal
- Telefone público
- E-mail público
- Telefone privado 1 com DDD
- Telefone privado 2 com DDD
- CEP

**Eventos incomuns:**

O campo `publicLocation` não atualiza no navegador, mas é atualizado no endpoint, que por sua vez atualiza no navegador.

**Não foram testados**

- Os campos de enviar imagens e arquivos.

2024-05-15 13:24 UTC, alessandrofeitoza approved these changes

2024-05-15 13:26 UTC, merged