Adds method update in api events
secultce/mapacultural pull request #195
Opened 2024-05-06 22:16 UTC by Akellymourab

#146

2024-05-06 22:26 UTC, Akellymourab commented
&#128295; - precisa de alguns ajustes

2024-05-09 19:26 UTC, henriquelopeslima commented on src/core/Entities/Event.php
Por que você está removendo isso?

2024-05-09 19:28 UTC, henriquelopeslima commented on app/src/Service/EventService.php
> +    private $serializer;
```suggestion
    private SerializerInterface $serializer;
```

2024-05-10 07:03 UTC, alessandrofeitoza commented on app/src/Service/EventService.php
> +        $eventUpdated = $this->serializer->denormalize($data, Event::class, null, ['object_to_populate' => $eventFromDB]);
acredito que se a gente usar `named arguments` e quebrar em algumas linhas, esse trecho ficará mais legivel, por exemplo:

```php
$eventUpdated = $this->serializer->denormalize(
    data: $data,
    type: Event::class,
    context: ['object_to_populate' => $eventFromDB] 
);
```

2024-05-10 07:03 UTC, alessandrofeitoza commented on app/src/Service/EventService.php
> +    public function update($id, $data): Event
estão faltando os tipos dos parametros

2024-05-10 07:04 UTC, alessandrofeitoza commented on app/src/Request/EventRequest.php
> +        return $data;
como a vida útil dessa variavel é muito curta, vc pode trocar por:
```php
return json_decode($jsonData, true);
```

2024-05-10 07:06 UTC, alessandrofeitoza requested changes
só alguns ajustes

2024-05-10 18:15 UTC, Akellymourab commented on src/core/Entities/Event.php
eu removi pois não está sendo usado.

2024-05-11 03:48 UTC, Akellymourab commented
Campos que não estão sendo atualizados após uma requisição PATCH

1. **telefonePublico**: Número de telefone público para contato.
2. **preco**: Preço do evento.
3. **traducaoLibras**: Indicação se haverá tradução para Libras (Língua Brasileira de Sinais).
4. **descricaoSonora**: Indicação se haverá descrição sonora para pessoas com deficiência visual.
5. **site**: Url do site relacionado ao evento.
6. **facebook**: Nome da página do evento no Facebook.
7. **twitter**: Nome da página do evento no Twitter.
8. **instagram**: Nome da página do evento no Instagram.
9. **linkedin**: Nome da página do evento no LinkedIn.
10. **vimeo**: Nome da página do evento no Vimeo.
11. **spotify**: Nome da página do evento no Spotify.
12. **youtube**: Nome da página do evento no YouTube.
13. **pinterest**: Nome da página do evento no Pinterest.
14. **subTitle**: Subtítulo ou slogan do evento.
15. **registrationInfo**: Informações sobre como se registrar para o evento.
16. **event_attendance**: Número de participantes esperados para o evento.
17. **telefonePublico**: Número de telefone público para contato.
18. **traducaoLibras**: Indicação se haverá tradução para Libras (Língua Brasileira de Sinais).
19. **descricaoSonora**: Indicação se haverá descrição sonora para pessoas com deficiência visual.

2024-05-14 12:30 UTC, henriquelopeslima approved these changes

2024-05-15 12:24 UTC, alessandrofeitoza approved these changes

2024-05-15 12:50 UTC, merged