Adds delete endpoint for Opportunity.
secultce/mapacultural pull request #198
Opened 2024-05-10 14:31 UTC by saracamilodev

2024-05-13 15:19 UTC, Akellymourab requested changes
apenas alguns ajustes

2024-05-13 15:19 UTC, Akellymourab commented on app/src/Controller/Api/OpportunityApiController.php
> +            }
acredito que a função `validateDelete` usada acima já esteja fazendo essa verificação de existência do opportunity.

2024-05-13 15:19 UTC, Akellymourab commented on app/src/Controller/Api/OpportunityApiController.php
> +            return new JsonResponse(null, JsonResponse::HTTP_NO_CONTENT);
Pode ser uma abordagem melhor retornar um array vazia após ser deletado com sucesso ao invés de null, ficaria dessa forma:
 ```
return new JsonResponse([], Response::HTTP_NO_CONTENT);
```

2024-05-13 15:19 UTC, Akellymourab commented on app/src/Controller/Api/OpportunityApiController.php
> +            return new JsonResponse(['error' => $exception->getMessage()], 400);
Para manter o padrão de usar os objetos `JasonResponse`, você pode fazer da seguinte forma: 
```
return new JsonResponse(['error' => $exception->getMessage()], Response::HTTP_BAD_REQUEST);
```

2024-05-13 15:19 UTC, Akellymourab commented on app/src/Repository/OpportunityRepository.php
> +        $this->mapaCulturalEntityManager->flush();
Apenas para evitar repetição de código você pode usar a sua função `save` que está um pouco mais acima e executar essa mesma ação na função atual. 
Você pode chamar o save da seguinte forma: 
```
$this->save($opportunity);
```

2024-05-13 15:19 UTC, Akellymourab commented on app/src/Service/OpportunityService.php
> +    }
Acredito que essa função não tem uma necessidade especifica nesse caso, ela basicamente está executando ações que em outras classes já estão sendo feitas. 
Você já está chamando o repository direto no controller, sem a necessidade de usar o service, com isso essa função pode ser apagada.

2024-05-13 15:19 UTC, Akellymourab commented on public/docs/v2/openapi.yaml
> +    $ref: './components/paths/opportunity/delete.yaml'
Em termos de estética de código de fato essa seria a melhor abordagem, mas percebemos que na renderização ele acaba não tendo o comportamento esperado, então uma boa alternativa seria criar um arquivo em `public/docs/v2/components/paths/opportunity` para adicionar os outros modelos de requisição que também usam `/opportunities/{id}` e então fazer referencia a esse arquivo para resolver esse pequeno bug de renderização da documentação.

2024-05-13 15:19 UTC, Akellymourab commented on public/docs/v2/openapi.yaml
> +    $ref: './components/paths/opportunity/delete.yaml'
um exemplo disso é mais abaixo em 
```
/projects/{id}:
    $ref: './components/paths/project/group-param-id.yaml'
```

2024-05-14 16:51 UTC, henriquelopeslima commented on app/src/Controller/Api/OpportunityApiController.php
> +            return new JsonResponse([], Response::HTTP_NO_CONTENT); // Retorna array vazio em caso de sucesso
Por favor, remover esse comentário aqui.

2024-05-14 16:51 UTC, henriquelopeslima commented on app/src/Controller/Api/OpportunityApiController.php
> +            return new JsonResponse(['error' => $exception->getMessage()], Response::HTTP_BAD_REQUEST); // Padroniza erros
E esse também.

2024-05-14 16:57 UTC, Akellymourab approved these changes

2024-05-14 17:35 UTC, henriquelopeslima approved these changes

2024-05-14 17:46 UTC, merged