Add new entity event.
secultce/mapacultural pull request #223
Opened 2024-05-21 18:30 UTC by Akellymourab

#159

2024-05-21 18:35 UTC, alessandrofeitoza commented on app/src/Entity/Event.php
> +    private string $longDescription;
como essa é `nullable`, precisamos deixar claro na declaração dos tipos, por exemplo:

`private ?string $longDescription = null;`

ou

`private null|string $longDescription = null`;

2024-05-21 18:36 UTC, alessandrofeitoza commented on app/src/Entity/Event.php
> +    private string $rules;
como tipo é `datetime`, acho que rola colocar `DateTime` (a classe) como tipo dessa coluna

2024-05-21 18:36 UTC, alessandrofeitoza requested changes
Acredito que nesse PR já possam vir os metodos getters e setters tbm

2024-05-22 17:37 UTC, saracamilodev approved these changes

2024-05-22 17:41 UTC, alessandrofeitoza approved these changes

2024-05-22 17:41 UTC, merged