Create new entity `Agents`
secultce/mapacultural pull request #239
Opened 2024-05-23 18:38 UTC by TalysonSoares

#157

2024-05-23 18:41 UTC, henriquelopeslima commented on app/src/Entity/Agent.php
> +    //    protected ??? $_geoLocation;
Por que deixou esse comentário?

2024-05-23 19:00 UTC, TalysonSoares commented on app/src/Entity/Agent.php
> +    //    protected ??? $_geoLocation;
Resolvido meu nobre!

2024-05-23 19:14 UTC, henriquelopeslima commented on app/src/Entity/Agent.php
> +    private int $_type;
```suggestion
    private int $type;
```

2024-05-23 19:14 UTC, henriquelopeslima commented on app/src/Entity/Agent.php
> +    private int $_type;
Est[a faltando o **get** e **set** dessa propriedade e pelo que vi de algumas outras, recomendo passar o olho novamente.

2024-05-23 20:06 UTC, TalysonSoares commented on app/src/Entity/Agent.php
> +    private int $_type;
Foi

2024-05-24 12:15 UTC, Akellymourab approved these changes

2024-05-24 12:31 UTC, alessandrofeitoza requested changes
algumas modificações

2024-05-24 12:31 UTC, alessandrofeitoza commented on app/src/Entity/Agent.php
> +    private GeoPoint $location;
add linha em branco

2024-05-24 12:31 UTC, alessandrofeitoza commented on app/src/Entity/Agent.php
> +    private Space $spaces;
```php
private iterable $spaces;
```

2024-05-24 12:31 UTC, alessandrofeitoza commented on app/src/Entity/Agent.php
> +    private AgentOpportunity $ownedOpportunities;
```php
private iterable $ownedOpportunities;
```

2024-05-27 13:09 UTC, alessandrofeitoza approved these changes

2024-05-27 13:09 UTC, merged