Add test refactoring.
secultce/mapacultural pull request #243
Opened 2024-05-24 16:40 UTC by Akellymourab

Resolve #235

2024-05-27 11:53 UTC, saracamilodev approved these changes

2024-05-27 15:31 UTC, alessandrofeitoza requested changes
Pronto, só alguns pontos.

- Lembra de rodar localmente os testes, precisamos que todos estejam passando. 
- Aqueles que tiverem quebrados, adiciona essa linha no inicio do método 
```php
        $this->markTestSkipped();
```

2024-05-27 15:31 UTC, alessandrofeitoza commented on app/tests/functional/AgentApiControllerTest.php
> +        $response = $this->client->request('DELETE', self::BASE_URL.'/2');
aqui dá pra usar o `Request::METHOD_DELETE`

2024-05-27 15:31 UTC, alessandrofeitoza commented on app/tests/functional/SpaceApiControllerTest.php
> +            'headers' => ['Content-Type' => 'application/json'],
Pensando agora com a mente, imaginei que dava pra isolar esse trecho em um outro lugar, talvez em no `AbstractTestCase::setUp()`

algo tipo:
```php
$this->client = HttpClient::create()->withOptions([
    'base_uri' => 'http://localhost',
    'headers' => [
        'Content-Type' => 'application/json',
    ],
]);
```

2024-05-28 15:59 UTC, Akellymourab commented
Agent Api Controller (App\Tests\AgentApiController)
 ✔ Get agents should retrieve a list
 ✔ Get one agent should retrieve a object
 ✔ Get agent types should retrieve a list
 ✘ Get agent opportunities should retrieve a list
   │
   │ Failed asserting that null is of type array.
   │
   │ /var/www/app/tests/functional/AgentApiControllerTest.php:49
   │
 ✘ Create agent should create an agent
   │
   │ Failed asserting that 400 matches expected 201.
   │
   │ /var/www/app/tests/functional/AgentApiControllerTest.php:67
   │
 ✘ Delete agent should return success
   │
   │ Failed asserting that 404 matches expected 204.
   │
   │ /var/www/app/tests/functional/AgentApiControllerTest.php:81
   │
 ↩ Update
 ✔ Update not founded resource

Event Api Controller (App\Tests\EventApiController)
 ✔ Get event types should retrieve a list
 ✔ Get one agent should retrieve a object
 ✘ Get events by spaces should retrieve a list
   │
   │ Failed asserting that null is of type array.
   │
   │ /var/www/app/tests/functional/EventApiControllerTest.php:40
   │
 ↩ Post event should create a new event
 ↩ Delete event should remove an event
 ↩ Update event should update an event
 ✔ Update not founded event resource

Opportunity Api Controller (App\Tests\OpportunityApiController)
 ✔ Get opportunities should retrieve a list
 ✔ Get one opportunity should retrieve a object

Project Api Controller (App\Tests\ProjectApiController)
 ✔ Get projects should retrieve a list
 ✔ Get one project should retrieve a object
 ✔ Create project should create a project
 ✘ Delete project should return success
   │
   │ Failed asserting that 400 matches expected 204.
   │
   │ /var/www/app/tests/functional/ProjectApiControllerTest.php:59
   │
 ✔ Update project should update a project
 ✔ Update not founded project resource

Seal Api Controller (App\Tests\SealApiController)
 ✔ Get seals should retrieve a list
 ✔ Get one seal should retrieve a object
 ✔ Create seal should return created seal
 ✘ Delete seal should return success
   │
   │ Failed asserting that 404 matches expected 204.
   │
   │ /var/www/app/tests/functional/SealApiControllerTest.php:55
   │
 ↩ Update
 ✔ Update not founded resource

Space Api Controller (App\Tests\SpaceApiController)
 ✔ Get spaces should retrieve a list
 ✔ Get one space should retrieve a object
 ↩ Create space should return created space
 ✘ Delete space should return success
   │
   │ Failed asserting that 404 matches expected 204.
   │
   │ /var/www/app/tests/functional/SpaceApiControllerTest.php:62
   │
 ↩ Update
 ✔ Update not founded resource

Welcome Api Controller (App\Tests\WelcomeApiController)
 ✔ Homepage from a p i
 ✔ Method d e l e t e from a p i
 ✔ Method p o s t from a p i
 ✔ Error response when method is not allowed

FAILURES!
Tests: 39, Assertions: 72, Failures: 7, Skipped: 7.

Testes Skippados : 

1)  App\Tests\AgentApiControllerTest::testUpdate

2)  App\Tests\EventApiControllerTest::testPostEventShouldCreateANewEvent

3)  App\Tests\EventApiControllerTest::testDeleteEventShouldRemoveAnEvent

4)  App\Tests\EventApiControllerTest::testUpdateEventShouldUpdateAnEvent

5)  App\Tests\SpaceApiControllerTest::testCreateSpaceShouldReturnCreatedSpace

6)  App\Tests\SpaceApiControllerTest::testUpdate

2024-05-29 00:54 UTC, alessandrofeitoza approved these changes

2024-05-29 00:55 UTC, merged