Add validation
secultce/mapacultural pull request #246
Opened 2024-05-27 12:20 UTC by henriquelopeslima

Resolve #230

2024-05-27 16:49 UTC, saracamilodev approved these changes

2024-05-27 18:23 UTC, alessandrofeitoza commented on app/src/Controller/Api/SealApiController.php
> +            'fields' => $exception->getFields()
Aqui faltou um `tab` para a endentação, e uma virgula ao final da linha dos `fields`

2024-05-27 18:23 UTC, alessandrofeitoza commented on app/src/Controller/Api/SealApiController.php
> +                'fields' => $exception->getFields()
faltou uma virgula aqui tbm

2024-05-27 18:23 UTC, alessandrofeitoza commented on app/src/DTO/Seal/SealInput.php
> +}
faltou uma linha vazia ao fim desse arquivo

2024-05-27 18:27 UTC, alessandrofeitoza commented on app/src/DTO/Seal/SealInput.php
> +final class SealInput
se o objetivo dessa classe é ser usada tanto nas requests de entrada (PATCH, PUT, POST), como nas de saída (GET), acredito então que um nome melhor seria `SealDto.php` ao invés de `SealInput`

e assim sendo, talvez não precise criar um novo diretório chamado Seal, apenas soltá-la dentro de `app/src/Dto/`

2024-05-27 18:28 UTC, alessandrofeitoza commented on app/src/Request/SealRequest.php
> +        if (count($violations) > 0) {
acho que isso não passará no code style, pois precisaria estar em yoda style:
```php
        if (0 < count($violations)) {
```

2024-05-27 18:29 UTC, alessandrofeitoza requested changes
apenas algumas correções.

2024-05-28 01:21 UTC, alessandrofeitoza approved these changes

2024-05-28 01:22 UTC, merged