Creating new Exceptions.
secultce/mapacultural pull request #250
Opened 2024-05-28 17:43 UTC by saracamilodev

2024-05-28 18:33 UTC, alessandrofeitoza requested changes
só alguns ajustes

2024-05-28 18:33 UTC, alessandrofeitoza commented on app/src/Exception/FieldInvalidException.php
> +    public function __construct(?string $message = null)
acredito que você possa receber um primeiro parametro `$fieldName` para ficar claro qual $field é invalido, tipo assim:

```php
public function __construct(string $fieldName, ?string $message = null)
{
    if (null === $message) {
        $message = "The field {$fieldName} is invalid.";
    }

    parent::__construct($message);
}
```

2024-05-28 18:33 UTC, alessandrofeitoza commented on app/src/Exception/FieldRequiredException.php
> +    public function __construct(?string $message = null)
o mesmo vale pra essa daqui

2024-05-28 18:38 UTC, TalysonSoares commented on app/src/Exception/InvalidRequestException.php
Acho que a implementação ficaria mais clara e concisa dessa forma:
```php
class InvalidRequestException extends Exception
{
    public function __construct(?string $message = 'The request is invalid')
    {
        parent::__construct($message, Response::HTTP_BAD_REQUEST);
    }
}

2024-05-28 18:40 UTC, TalysonSoares commented on app/src/Exception/RequiredIdParamException.php
Isso também se aplica aos outros

2024-05-28 20:41 UTC, TalysonSoares approved these changes

2024-05-29 14:52 UTC, alessandrofeitoza approved these changes

2024-05-29 15:50 UTC, merged