Create a method to return json from the test fixtures.
secultce/mapacultural pull request #255
Opened 2024-05-29 12:31 UTC by TalysonSoares

#231

2024-05-29 18:11 UTC, alessandrofeitoza requested changes

2024-05-29 18:11 UTC, alessandrofeitoza commented on app/tests/fixtures/AbstractTestFixtures.php
> +    }
acredito que aqui a gente possa fazer a versão reduzida

```php
public function __construct (
    private array $data
) {
}
```

2024-05-29 18:11 UTC, alessandrofeitoza commented on app/tests/functional/AgentApiControllerTest.php
> +        $requestBody = $agentTestFixtures->json();
o uso dessa variavel é apenas uma vez, então essa linha é desnecessária

2024-05-29 18:11 UTC, alessandrofeitoza commented on app/tests/functional/AgentApiControllerTest.php
> +            'body' => $requestBody,
por conta da não mais criação da variavel, aqui vc pode chamar diretamente:
`'body' = > $agentTestFixtures->json(),`

2024-05-29 18:11 UTC, alessandrofeitoza commented on app/tests/functional/AgentApiControllerTest.php
> +        foreach ($requestArray as $key => $value) {
o mesmo vale pra cá:
```php
foreach ($agentTestFixtures->toArray() as $key => $value) {
```

2024-05-30 14:25 UTC, alessandrofeitoza approved these changes

2024-05-30 14:27 UTC, Akellymourab approved these changes

2024-05-30 14:50 UTC, saracamilodev approved these changes

2024-05-30 14:52 UTC, merged