Adds Exception in Space, Opportunity, Seal.
secultce/mapacultural pull request #267
Opened 2024-06-03 13:00 UTC by saracamilodev

2024-06-04 12:33 UTC, Akellymourab approved these changes

2024-06-04 17:40 UTC, alessandrofeitoza requested changes
algumas melhorias

2024-06-04 17:40 UTC, alessandrofeitoza commented on app/src/Controller/Api/OpportunityApiController.php
> +            }
Talvez seja melhor mover essa validação para o método `find()` lá dentro do repository

2024-06-04 17:40 UTC, alessandrofeitoza commented on app/src/Controller/Api/OpportunityApiController.php
> +                throw new ResourceNotFoundException('Opportunity not found.');
Já que a Exception é especifica para `resources` que não existem, basta apenas chamar por:
```php
throw new ResourceNotFoundException();
```

2024-06-04 17:40 UTC, alessandrofeitoza commented on app/src/Controller/Api/OpportunityApiController.php
>          }
Sugiro manter um mesmo "catch" já que eles retornam  a mesma coisa:

```php    
} catch (Exception $exception) {
       return new JsonResponse(['error' => $exception->getMessage()], Response::HTTP_BAD_REQUEST);
}
```

2024-06-04 17:40 UTC, alessandrofeitoza commented on app/src/Controller/Api/OpportunityApiController.php
> +            return new JsonResponse(['error' => $exception->getMessage()], Response::HTTP_BAD_REQUEST);
aqui tbm vale a pena um só "catch"

2024-06-04 17:40 UTC, alessandrofeitoza commented on app/src/Controller/Api/SealApiController.php
> +                throw new FieldRequiredException('The required field is missing.');
já que a Exception precisa receber apenas o parametro "field", então basta fazer:
```php
throw new FieldRequiredException('required_field');
```

2024-06-04 17:40 UTC, alessandrofeitoza commented on app/src/Controller/Api/SealApiController.php
> +                throw new FieldInvalidException('The field is invalid.');
o mesmo vale pra cá, apenas o nome do campo.

2024-06-04 17:40 UTC, alessandrofeitoza commented on app/src/Controller/Api/SpaceApiController.php
> +            throw new ResourceNotFoundException('Space not found.');
aqui tbm não precisa da mensagem, basta deixar vazio os parametros

2024-06-04 17:40 UTC, alessandrofeitoza commented on app/src/Controller/Api/SpaceApiController.php
> +                throw new FieldInvalidException('The name field is invalid.');
apenas passar o parametro "name"

2024-06-04 17:40 UTC, alessandrofeitoza commented on app/src/Controller/Api/SpaceApiController.php
>              return new JsonResponse(['error' => $exception->getMessage()], 400);
ao invés de usar o numero 400, já troca aqui por `Response::HTTP_BAD_REQUEST`

2024-06-08 02:50 UTC, alessandrofeitoza approved these changes

2024-06-08 02:50 UTC, merged