Implement Update Functionality for Terms Endpoint ✏️
secultce/mapacultural pull request #299
Opened 2024-06-12 18:12 UTC by TalysonSoares

Fix #265

2024-06-12 19:49 UTC, alessandrofeitoza approved these changes

2024-06-13 10:27 UTC, Akellymourab requested changes

2024-06-13 10:27 UTC, Akellymourab commented on public/docs/v2/components/paths/term/update.yaml
> +          $ref: '../../responses/term/created.yaml'
apenas adicionar uma linha no final do arquivo para manter o padrão
```suggestion
          $ref: '../../responses/term/created.yaml'
          
```

2024-06-13 10:27 UTC, Akellymourab commented on public/docs/v2/components/paths/term/group-param-id.yaml
>    $ref: './delete.yaml'
apenas adicionar uma linha no final do arquivo para manter o padrão
```suggestion
  $ref: './delete.yaml'
  
```

2024-06-13 10:27 UTC, Akellymourab commented on app/src/Service/TermService.php
> +
adiciona a função update lá no `app/src/Service/Interface/TermServiceInterface.php`
![image](https://github.com/secultce/mapacultural/assets/101601082/74fb72cc-c469-435c-9b7a-746e0291eb1f)
Pois o controller está usando o service interface e não diretamente a classe service.

2024-06-13 13:08 UTC, alessandrofeitoza commented on app/tests/Functional/TermApiControllerTest.php
> +    public function testUpdate(): void
o nome do teste precisa ser mais expressivo

2024-06-13 13:10 UTC, alessandrofeitoza commented on app/tests/Functional/TermApiControllerTest.php
> +    public function testTermNotFound(): void
esse tbm, tipo `testUpdateATermThatNotExists`

2024-06-13 13:12 UTC, alessandrofeitoza commented on app/src/Request/TermRequest.php
> +        return $this->validateTerm('post');
acredito que isso `post` possa ser uma const nessa classe (ou em outra), ou usar a classe `Request` do Symfony que já traz essas palavras chaves

2024-06-13 13:34 UTC, Akellymourab approved these changes

2024-06-13 14:40 UTC, merged