Refactoring the Delete of Entities.
secultce/mapacultural pull request #303
Opened 2024-06-13 16:44 UTC by saracamilodev

2024-06-13 17:44 UTC, alessandrofeitoza requested changes

2024-06-13 17:44 UTC, alessandrofeitoza commented on app/src/Controller/Api/AgentApiController.php
> +        $this->repository->removeById($id);
acredito que aqui ou chama um ou chama o outro

2024-06-13 17:44 UTC, alessandrofeitoza commented on app/src/Controller/Api/EventApiController.php
> +        $this->repository->removeById($id);
o mesmo vale pra cá, ou um, ou outro

2024-06-13 17:44 UTC, alessandrofeitoza commented on app/src/Controller/Api/EventApiController.php
> +    public function remove($params): JsonResponse
aqui aproveita pra declarar o tipo do param, `array $params`

2024-06-13 17:44 UTC, alessandrofeitoza commented on app/src/Repository/EventRepository.php
> +    public function softDelete(Event $event): void
lembra que o principal objetivo desse PR é justamente acabar com esse termo `softDelete`, é pra se chamar apenas `delete` ou `remove` ou `removeById`

2024-06-13 18:04 UTC, henriquelopeslima commented on app/src/Repository/EventRepository.php
> +    public function softDelete(Event $event): void
Eu usaria ou **_remove_** ou **_delete_**, porque **_removeById_** da a entender que será enviado um id, no entanto, passamos um **_objeto_** para o repositório.

2024-06-15 17:23 UTC, alessandrofeitoza approved these changes

2024-06-15 17:58 UTC, merged